<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <title>The Chris Brake Show Sound Board Cliporater Madness!!!!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="js/library/jquery-ui/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" media="screen">
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet" media="screen">
    <link href="js/library/font-awesome/css/font-awesome.min.css" rel="stylesheet" media="screen">
    <link href="css/toastr.min.css" rel="stylesheet" media="screen">

    <link href="css/site.css" rel="stylesheet" media="screen">

    <script src="js/library/jPhong.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="js/library/html5shiv.js"></script>
    <script src="js/library/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<?php echo $this->content; ?>
<?php echo $this->inlineScript() ?>
</body>

</html>
